name: docs (build)

on:
  pull_request:
    branches:
      - main
    paths:
      - .pre-commit-config.yaml
      - .github/workflows/docs_build.yml
      - '**.py'
      - '**.ipynb'
      - '**.js'
      - '**.html'
      - uv.lock
      - pyproject.toml
      - '**.rst'
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Install uv
        uses: astral-sh/setup-uv@1edb52594c857e2b5b13128931090f0640537287
        with:
          # Install a specific version of uv.
          version: "0.5.21"
          enable-cache: true

      - name: "Set up Python"
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38
        with:
          python-version-file: ".python-version"

      - name: Install the project
        run: uv sync --all-extras --all-groups

      - name: Build docs
        run: cd docs && rm -rf source/reference/api/_autosummary && uv run make html
